### ISSUE TITLE
Begin 2017 Nomination/Voting Process

### ISSUE THREAD

**Issue by caniszczyk** [cncf/awards#1]
It's time to to start the CNCF community awards process again!

https://twitter.com/kelseyhightower/status/796580410830393344

The goal would be to start nominations in mid October, have voting close mid November at the latest.

**Comment by caniszczyk** [comment]
@idvoretskyi can you come up with a timeline here for nominations etc, we're getting close to mid October

**Comment by idvoretskyi** [comment]
We are done with 2017! https://github.com/cncf/awards/pull/2
