### ISSUE TITLE
End User Award for KubeCon EU 2021

### ISSUE THREAD

**Issue by caniszczyk** [cncf/awards#17]
@oicheryl just throwing this on your queue even though we are more than a few months out :)

**Comment by kgamanji** [comment]
Linking: https://github.com/cncf/ecosystem/issues/40

**Comment by oicheryl** [comment]
Nominations: February 12 - 26
Voting: 2nd - 9th of March

Nomination form: https://www.surveymonkey.co.uk/r/WSF2DYB

**Comment by caniszczyk** [comment]
done: https://www.cncf.io/announcements/2021/05/05/cloud-native-computing-foundation-grants-spotify-the-top-end-user-award/
