### ISSUE TITLE
Create awards for KubeCon/CloudNativeCon North America

### ISSUE THREAD

**Issue by caniszczyk** [cncf/awards#5]
Let's open up nominations in September, close end of November.

cc: @idvoretskyi

**Comment by idvoretskyi** [comment]
Let's do the following:

### Schedule                                                                                                                        
                                                                                                                                    
| Date         | Event                                             |                                                                
|--------------|---------------------------------------------------|                                                                
| September 21 | Awards announcement; Nominations Begin            |                                                                
| October 19   | Nominations Closing                               |                                                                
| November 1   | Voting Opens                                      |                                                                
| November 15  | Voting Closes                                     |                                                                
| Dec 11-13    | Announcement of Results at KubeCon/CloudNativeCon |

**Comment by caniszczyk** [comment]
@idvoretskyi make sure to sketch out the rules of how nominations and voting works for each category: Top Committer, Top Ambassador, Top End User

**Comment by dankohn** [comment]
I thought top end user won't be awarded again until Barcelona.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by idvoretskyi** [comment]
Announced - https://www.cncf.io/blog/2018/10/08/annual-cncf-community-awards-nominations-kick-off-winners-to-be-recognized-at-kubecon-cloudnativecon-seattle/.

This issue can be closed.

**Comment by caniszczyk** [comment]
@idvoretskyi can you update the README with the winners :)?

**Comment by idvoretskyi** [comment]
https://github.com/cncf/awards/pull/7

**Comment by idvoretskyi** [comment]
@caniszczyk we may close this one, we are done with https://github.com/cncf/awards/pull/7 :)
