### ISSUE TITLE
Top Maintainer / Committer / Ambassador Awards: KubeCon NA 2019

### ISSUE THREAD

**Issue by caniszczyk** [cncf/awards#9]

**Comment by amye** [comment]
Timeline: 
Nominations open September 11, 2019
Nominations close October 1, 2019

Announced on November 17, 2019

**Comment by caniszczyk** [comment]
**CNCF Top Ambassador**

https://www.surveymonkey.com/r/KWHTTDC

A champion for the cloud native space, this individual helps spread awareness of the CNCF (and its incubated projects). The CNCF Ambassador leverages multiple platforms, both online as well as speaking engagements, driving interest and excitement around the project.

**CNCF Top Committer**: 

https://www.surveymonkey.com/r/KS3X3LK

This will recognize excellence in technical contributions to CNCF and its projects. The CNCF Top Committer has made key commits to projects and, more importantly, contributes in a way that benefits the project neutrally as a whole.

**CNCF Chop Wood Carry Water**: 

https://www.surveymonkey.com/r/KQTWGXT

This is given to a community member who helps behind the scenes, dedicating countless hours of their time to open source projects + completing often thankless tasks for the ecosystem’s benefit. The winner of this award will be chosen by the TOC and CNCF Staff.

Nominations will open TODAY, and close on October 2nd. We'll be announcing the awards at KubeCon + CloudNativeCon San Diego. Voting (open from October 2nd) will be performed using the CIVS tool, using emails from the CNCF database for the following groups:

_CNCF Ambassadors are eligible to vote for the Top Ambassador
CNCF Maintainers are eligible to vote for the Top Committer_

**Comment by caniszczyk** [comment]
https://www.cncf.io/announcement/2019/11/19/cloud-native-computing-foundation-announces-2019-community-awards-winners/
